<b>Note</b>: Pada kuis kali ini kita akan menggunakan data diamonds.csv yang bisa kalian download [disini](https://drive.google.com/uc?export=download&id=1qQiM9utQUThTPq8jk8stPMh_y2zfqYOd). setelah di download, kalian pindahkan data tersebut satu level dengan direktori file notebook ini.


In [2]:
import pandas as pd
df = pd.read_csv('diamonds-3.csv')
df.drop('Unnamed: 0', axis=1, inplace=True) #hilangkan kolom unnamed

In [3]:
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [1]:
df.swap(df.row[1],df.row[2],inplace=True)

NameError: name 'df' is not defined

Columns Metadata:

carat: berat diamond

cut: kualitas diamond

color: warna diamond

clarity: level kemurnian diamonds

depth: tinggi dari diamond tabel

table: lebar  dari diamond tabel

price: harga diamond ($US)

x: panjang

y: lebar

z: kedalaaman

<h2>Soal 1: Process Grouping</h2>

Jelaskan prosess yang terjadi dalam grouping data menggungkan method <b>groupby()</b> dari pandas.

jawab: grouping adalah teknik memisahkan data berdasarkan kriteria tertentu atau definisi lainnya adalah melakukan mapping suatu data terhadap suatu group. Ketika melakukan grouping, ada beberapa proses yang terjadi secara berurutan, yaitu:
- Splitting : memisahkan data ke dalam suatu grup berdasarkan kriteria tertentu.
- Applying : melakukan suatu operasi terhadap sekumpulan data di grup-grup tersebut.
- Combining : menggabungkan data menjad suatu struktur baru

<h2>Soal 2: Grouping All Column</h2>
    
Group data diamond berdasarkan cut (kualitas), lakukan aggregasi dengan fungsi rata2.

Kemudian jawab pertanyaan berikut.
- Berapa harga rata2 dari diamond berkualitas Premium

Expected Output:

![alt text](https://drive.google.com/uc?id=1GKanuLzNv_pYBFVRBmQywxQw39uQBvSl)

In [8]:
# code here
# Grouping data by 'cut'
byclass = df.groupby('cut').mean()
print(byclass,'\n')

prem = byclass['price']['Premium']
print('Harga rata-rata diamond kualitas premium adalah: ',round(prem,4))

              carat      depth      table        price         x         y  \
cut                                                                          
Fair       1.046137  64.041677  59.053789  4358.757764  6.246894  6.182652   
Good       0.849185  62.365879  58.694639  3928.864452  5.838785  5.850744   
Ideal      0.702837  61.709401  55.951668  3457.541970  5.507451  5.520080   
Premium    0.891955  61.264673  58.746095  4584.257704  5.973887  5.944879   
Very Good  0.806381  61.818275  57.956150  3981.759891  5.740696  5.770026   

                  z  
cut                  
Fair       3.982770  
Good       3.639507  
Ideal      3.401448  
Premium    3.647124  
Very Good  3.559801   

Harga rata-rata diamond kualitas premium adalah:  4584.2577


jawab: Harga rata-rata diamond kualitas premium adalah:  4584.2577

<h2>Soal 3: Grouping Some Column base on Multiple Criteria</h2>
    
Lakukan groupby pada data berdasarkan kriteria cut (kualitas) dan color (warna) secara berurutan, dengan aggregasi pada column carat, table, dan price saja. dengan fungsi agregasi rata-rata.

Kemudian jawab pertanyaan berikut:
- Berapa harga diamond yang berkriteria premium dan berwarna J
- Berapa nilai dari carat diamond yang berkriteria very good dan berwarna H

Expected Output:

Note: gambar hanya sebagaian dari keseluruhan data

![alt text](https://drive.google.com/uc?id=1XB_uHor7ZCPQUH9uQjSfd6aC6_yJnjh9)

In [4]:
# code here
mult = df.groupby(['cut','color']).mean()
multfin = mult.loc[:, ['carat','table','price']]
print(multfin,'\n')

# harga rata-rata diamond kriteria premium dan berwarna J
#no3b = mult.get_group(('Premium','J'))
no3b = mult.loc['Premium','J']['price']
print('Harga rata-rata diamond kriteria premium berwarna J adalah %f'% round(no3b, 4))

# carat diamond kriteria very good dan berwarna H
no3c = mult.loc['Very Good','H']['carat']
print('Carat rata-rata diamond kriteria very good berwarna H adalah %f '%round(no3c,4))

                    carat      table        price
cut       color                                  
Fair      D      0.920123  58.969325  4291.061350
          E      0.856607  59.364732  3682.312500
          F      0.904712  59.453205  3827.003205
          G      1.023822  58.773248  4239.254777
          H      1.219175  58.696370  5135.683168
          I      1.198057  59.237143  4685.445714
          J      1.341176  58.917647  4975.655462
Good      D      0.744517  58.541541  3405.382175
          E      0.745134  58.779957  3423.644159
          F      0.775930  58.910891  3495.750275
          G      0.850896  58.471986  4123.482204
          H      0.914729  58.611111  4276.254986
          I      1.057222  58.773946  5078.532567
          J      1.099544  58.813029  4574.172638
Ideal     D      0.565766  55.965632  2629.094566
          E      0.578401  55.967461  2597.550090
          F      0.655829  55.924203  3374.939362
          G      0.700715  55.902375  3720.706388


jawab: 
- Harga rata-rata diamond kriteria premium berwarna J adalah 6294.5916
- Carat rata-rata diamond kriteria very good berwarna H adalah 0.9159

<h2>Soal 4: Group By Multiple Aggregate Base on Multiple Criteria</h2>
    
Lakukan groupby pada data berdasarkan kriteria cut(kualitas) dan color (warna) secara berurutan kemudian aggregasi objek group by nya dengan fungsi rata2 dan median.

Kemudian Jawab Pertanyaan berikut:

- Berapa nilai median dari harga diamond berkualitas good dan berwarna F

Expected Output:

Note : gambar hanya sebagaian dari keseluruhan data

![alt text](https://drive.google.com/uc?id=1fUPIse5ELrzj26ZyWBqsAVOUb6yf7UoD)

In [14]:
# code here
import numpy as np
no4 = df.groupby(['cut','color']).agg([np.mean, np.median]) #.rename(columns={'mean':'rataan', 'median'='nilai tengah'})
print(no4)

no4b = no4.loc['Good','F']['price','median']
print('Median harga dari diamond kualitas Good berwarna F adalah ', round(no4b,4))

                    carat             depth             table         \
                     mean median       mean median       mean median   
cut       color                                                        
Fair      D      0.920123  0.900  64.048466   64.8  58.969325   58.0   
          E      0.856607  0.900  63.319643   64.8  59.364732   59.0   
          F      0.904712  0.900  63.508013   64.8  59.453205   59.0   
          G      1.023822  0.980  64.339809   65.0  58.773248   58.0   
          H      1.219175  1.010  64.585149   65.1  58.696370   58.0   
          I      1.198057  1.010  64.220571   65.1  59.237143   58.0   
          J      1.341176  1.030  64.357143   65.0  58.917647   58.0   
Good      D      0.744517  0.700  62.365710   63.4  58.541541   58.0   
          E      0.745134  0.700  62.203751   63.3  58.779957   58.0   
          F      0.775930  0.710  62.202310   63.2  58.910891   59.0   
          G      0.850896  0.900  62.526636   63.4  58.471986   

jawab: Median harga dari diamond kualitas Good berwarna F adalah  2647.0

<h2>Soal 5: Group By With Different Aggregation for specific Column</h2>
    
Lakukan groupby pada data berdasarkan criteria cut(kualitas), kemudian aggreagate dengan fungsi max pada column price dan fungsi min pada column carat.

Kemudian Jawab Pertanyaan berikut:

- Berapa nilai max dari price untuk diamond berkualitas Ideal

Expected Output:

![alt text](https://drive.google.com/uc?id=1B_z5PBkLe4hNJJJV3JgDGP9G--llytKf)

In [10]:
# code here
no5 = df.groupby('cut').agg({'price': 'max',
                               'carat': 'min'})
print(no5,'\n')
no5b = no5.loc['Ideal']['price']
print('Harga maksimum diamond kualitas ideal adalah ',no5b)

           price  carat
cut                    
Fair       18574   0.22
Good       18788   0.23
Ideal      18806   0.20
Premium    18823   0.20
Very Good  18818   0.20 

Harga maksimum diamond kualitas ideal adalah  18806.0


jawab: Harga maksimum diamond kualitas ideal adalah  18806.0

<h2>Soal 6: Group By With Custom Function</h2>
    
Lakukan groupby pada data berdasarkan criteria cut(kualitas), kemudian lakukan aggregasi dengan fungsi standar deviasi pada column carat dan fungsi rentang nilai antara max dan min pada column price.

Kemudian jawab pertanyaan berikut:
- Berapa selisih harga tertinggi dan terendah dari diamond berkualitas Premium

Expected Output:

![alt text](https://drive.google.com/uc?id=1bl6_8KryXCxLfzpAf4YF80Qvt15a3uQ6)

In [15]:
# code here
no6 = df.groupby('cut').agg({'price' : lambda x: x.max() - x.min(),
                            'carat' : np.std})
print(no6,'\n')
no6b = no6.loc['Premium']['price']
print('Selisih harga tertinggi dan terendah dari diamond berkualitas Premium adalah ',no6b)

           price     carat
cut                       
Fair       18237  0.516404
Good       18461  0.454054
Ideal      18480  0.432876
Premium    18497  0.515262
Very Good  18482  0.459435 

Selisih harga tertinggi dan terendah dari diamond berkualitas Premium adalah  18497.0


jawab: Selisih harga tertinggi dan terendah dari diamond berkualitas Premium adalah  18497.0

In [16]:
def maxmin(x):
    return x.max()-x.min()
# maxmin.__name__ = 'Rentang harga'

aggregation = {
    'Std carat': pd.NamedAgg(column='carat', aggfunc=np.std),
    'Rentang harga': pd.NamedAgg(column='price', aggfunc=maxmin)} #supaya bisa applying NamedAgg, pandasnya update dulu
df.groupby('cut').agg(**aggregation)


Std carat  Rentang harga
cut                                
Fair        0.516404          18237
Good        0.454054          18461
Ideal       0.432876          18480
Premium     0.515262          18497
Very Good   0.459435          18482